### PR TITLE
Added resource - markdown.

### PR DESCRIPTION
**Pull request by OliveiraDCI**
Added a resource link for a nice website to create markdown formatted text easily.

### CODE REVIEW

**Review by HelonDCI — CHANGES_REQUESTED** [review]
I'd consider this more of a tool than a resource. It doesn't look like there's an existing category for it so you should create a new subcategory under `Tools and Apps`.

**Review by HelonDCI — CHANGES_REQUESTED** [review]
The name should also be changed to `readme.so` instead of `markdown`

**Comment by OliveiraDCI** [comment]
Made requested changes, only difference is that I included the item in 'Miscellaneous' instead of creating a new tool list title. Hope that's all right, otherwise please let me know and I'll do exactly as you suggested. Thank you for your feedback.

**Comment by OliveiraDCI** [comment]
closed pull request accidentally, just reopened and kept the comment so it can be reviewed.

**Review by alinaincodeland — APPROVED** [review]

**Review by alinaincodeland — APPROVED** [review]

**Review by HelonDCI — APPROVED** [review]
Approving this but I do think we should create another category for `editors`

**Pull request merged**
