### PR TITLE
Added resource line - Password Manager

### PR DESCRIPTION
**Pull request by LalaChristl**
I think Bitwarden should be added as a resource because it saves time and can be used on multiple devices for free. 

https://bitwarden.com/

### CODE REVIEW

**Review by OliveiraDCI — APPROVED** [review]
Lgtm

**Comment by OliveiraDCI** [comment]
Your contribution is helpful and seems like it follows the project guidelines.

**Review by OliveiraDCI — APPROVED** [review]
Lgtm.

**Comment by HelonDCI** [comment]
lgtm @HelonDCI please merge

**Review by OliveiraDCI — APPROVED** [review]
yes

**Review by HelonDCI — APPROVED** [review]

**Pull request merged**
