### PR TITLE
New sub title for Editors

### PR DESCRIPTION
**Pull request by OliveiraDCI**
Under the Tools and Apps, created new subtitle for Editors and moved my previous contribution there, according to change request from Helon. Also added a minor change in Lala's contribution, with a bullet point before item name and description.

### CODE REVIEW

**Review by LalaChristl — COMMENTED** [review]
looks fine although it does not mention in the contribution guidelines that the resources should be bulleted.

**Comment by HelonDCI** [comment]
@OliveiraDCI @LalaChristl I fixed a heading that got deleted with the last merge so now you have a merge conflict to fix here🤯

**Review by LalaChristl — COMMENTED** [review]
lgtm

**Review by LalaChristl — COMMENTED** [review]
lgtm

**Review by OliveiraDCI — COMMENTED** [review]
merging conflict resolved.
@HelonDCI please review if merge conflict was resolved correctly.

**Review by HelonDCI — APPROVED** [review]
lgtm

**Pull request merged**
